name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
  # What's Changed

  $CHANGES
categories:
  - title: 🚀 Enhancements
    labels:
      - type/enhancement
  - title: 🐛 Bug Fixes
    label: type/bug
  - title: 📖 Documentation
    label: type/documentation
  - title: 🧹 Housekeeping
    labels:
      - type/housekeeping
  - title: 📦 Dependency updates
    label: type/dependency-upgrade