prerelease: true
name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
  # What's Changed

  $CHANGES
categories:
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: 📖 Documentation
    label: 'documentation'
  - title: '🧹 Housekeeping'
    labels:
      - 'housekeeping'
  - title: '📦 Dependency updates'
    label: 'dependency-upgrade'