sections:
  - title: "Bug Fixes"
    emoji: "🐞"
    labels: ["bug"]
  - title: "Enhancements"
    emoji: "⭐"
    labels: ["enhancement"]
  - title: "Dependency Upgrades"
    emoji: "🔨"
    labels: ["dependency-upgrade"]
  - title: "Documentation"
    emoji: "📔"
    labels: ["documentation"]
