# Trigger the workflow on milestone events
on:
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create release notes from milestone ${{ github.event.milestone.title }}
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"
      - name: deploy release notes for milestone ${{ github.event.milestone.title }}
        uses: ncipollo/release-action@v1
        with:
          replacesArtifacts: false
          allowUpdates: true
          bodyFile: temp_release_notes/${{ github.event.milestone.title }}.md
          draft: false
          tag: ${{ github.event.milestone.title }}
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}